import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:shared_preferences/shared_preferences.dart';

const supportedAppLocales = <Locale>[
  Locale('zh'),
  Locale('en'),
  Locale('fr'),
  Locale('de'),
  Locale('nl'),
  Locale('es'),
  Locale('ko'),
  Locale('ja'),
  Locale('it'),
  Locale('ru'),
];

const appLanguageNames = <String, String>{
  'zh': '中文',
  'en': 'English',
  'fr': 'Français',
  'de': 'Deutsch',
  'nl': 'Nederlands',
  'es': 'Español',
  'ko': '한국어',
  'ja': '日本語',
  'it': 'Italiano',
  'ru': 'Русский',
};

const _languageIndexes = <String, int>{
  'en': 0,
  'fr': 1,
  'de': 2,
  'nl': 3,
  'es': 4,
  'ko': 5,
  'ja': 6,
  'it': 7,
  'ru': 8,
};

const _translations = <String, List<String>>{
  '役次元-画地为牢': [
    'Yokidimension · Bound by the Line',
    'Yokidimension · Cercle interdit',
    'Yokidimension · Im Bannkreis',
    'Yokidimension · Binnen de grens',
    'Yokidimension · Dentro del límite',
    '역차원 · 경계의 감옥',
    '役次元・境界の檻',
    'Yokidimension · Dentro il confine',
    'Yokidimension · В границах',
  ],
  '画地为牢': [
    'Bound by the Line',
    'Cercle interdit',
    'Bannkreis',
    'Binnen de grens',
    'Dentro del límite',
    '경계의 감옥',
    '境界の檻',
    'Dentro il confine',
    'В границах',
  ],
  '本局结果': [
    'Session results',
    'Résultats',
    'Ergebnis',
    'Resultaten',
    'Resultados',
    '게임 결과',
    '今回の結果',
    'Risultati',
    'Результаты',
  ],
  'EMS 设备': [
    'EMS device',
    'Appareil EMS',
    'EMS-Gerät',
    'EMS-apparaat',
    'Dispositivo EMS',
    'EMS 기기',
    'EMS デバイス',
    'Dispositivo EMS',
    'Устройство EMS',
  ],
  '连接设备': [
    'Connect device',
    'Connecter l’appareil',
    'Gerät verbinden',
    'Apparaat verbinden',
    'Conectar dispositivo',
    '기기 연결',
    'デバイス接続',
    'Connetti dispositivo',
    'Подключить устройство',
  ],
  '游戏中': [
    'Running',
    'En cours',
    'Läuft',
    'Actief',
    'En curso',
    '진행 중',
    '進行中',
    'In corso',
    'Идёт игра',
  ],
  '已暂停': [
    'Paused',
    'En pause',
    'Pausiert',
    'Gepauzeerd',
    'En pausa',
    '일시 정지',
    '一時停止',
    'In pausa',
    'Пауза',
  ],
  '语言': [
    'Language',
    'Langue',
    'Sprache',
    'Taal',
    'Idioma',
    '언어',
    '言語',
    'Lingua',
    'Язык',
  ],
  '切换摄像头': [
    'Switch camera',
    'Changer de caméra',
    'Kamera wechseln',
    'Camera wisselen',
    'Cambiar cámara',
    '카메라 전환',
    'カメラ切替',
    'Cambia fotocamera',
    'Сменить камеру',
  ],
  '准备中…': [
    'Preparing…',
    'Préparation…',
    'Vorbereitung…',
    'Voorbereiden…',
    'Preparando…',
    '준비 중…',
    '準備中…',
    'Preparazione…',
    'Подготовка…',
  ],
  '开始游戏': [
    'Start game',
    'Démarrer',
    'Spiel starten',
    'Start spel',
    'Iniciar juego',
    '게임 시작',
    'ゲーム開始',
    'Avvia gioco',
    'Начать игру',
  ],
  '连接 EMS 设备': [
    'Connect EMS device',
    'Connecter l’appareil EMS',
    'EMS-Gerät verbinden',
    'EMS-apparaat verbinden',
    'Conectar dispositivo EMS',
    'EMS 기기 연결',
    'EMS デバイス接続',
    'Connetti dispositivo EMS',
    'Подключить EMS',
  ],
  '设置强度': [
    'Set intensity',
    'Régler l’intensité',
    'Intensität einstellen',
    'Intensiteit instellen',
    'Ajustar intensidad',
    '강도 설정',
    '強度設定',
    'Imposta intensità',
    'Настроить интенсивность',
  ],
  '暂停': [
    'Pause',
    'Pause',
    'Pause',
    'Pauze',
    'Pausa',
    '일시 정지',
    '一時停止',
    'Pausa',
    'Пауза',
  ],
  '继续游戏': [
    'Resume',
    'Reprendre',
    'Fortsetzen',
    'Hervatten',
    'Continuar',
    '계속하기',
    '再開',
    'Riprendi',
    'Продолжить',
  ],
  '结束': [
    'End',
    'Terminer',
    'Beenden',
    'Stoppen',
    'Finalizar',
    '종료',
    '終了',
    'Termina',
    'Завершить',
  ],
  '自由圈画': [
    'Freehand',
    'Tracé libre',
    'Freihand',
    'Vrij tekenen',
    'Dibujo libre',
    '자유 그리기',
    'フリーハンド',
    'Disegno libero',
    'Свободная зона',
  ],
  '矩形画区': [
    'Rectangle',
    'Rectangle',
    'Rechteck',
    'Rechthoek',
    'Rectángulo',
    '사각 영역',
    '長方形',
    'Rettangolo',
    'Прямоугольник',
  ],
  '重画区域': [
    'Redraw area',
    'Redessiner la zone',
    'Bereich neu zeichnen',
    'Zone opnieuw tekenen',
    'Redibujar zona',
    '영역 다시 그리기',
    '領域を描き直す',
    'Ridisegna area',
    'Перерисовать область',
  ],
  '请进入监测区域': [
    'Enter the monitored area',
    'Entrez dans la zone surveillée',
    'Überwachungsbereich betreten',
    'Ga naar het bewakingsgebied',
    'Entra en el área vigilada',
    '감지 영역에 들어가세요',
    '監視エリアに入ってください',
    'Entra nell’area monitorata',
    'Войдите в зону контроля',
  ],
  '取消': [
    'Cancel',
    'Annuler',
    'Abbrechen',
    'Annuleren',
    'Cancelar',
    '취소',
    'キャンセル',
    'Annulla',
    'Отмена',
  ],
  '剩余时间': [
    'Time remaining',
    'Temps restant',
    'Verbleibende Zeit',
    'Resterende tijd',
    'Tiempo restante',
    '남은 시간',
    '残り時間',
    'Tempo rimanente',
    'Осталось времени',
  ],
  '模拟触发': [
    'Triggers',
    'Déclenchements',
    'Auslösungen',
    'Triggers',
    'Activaciones',
    '작동 횟수',
    'トリガー回数',
    'Attivazioni',
    'Срабатывания',
  ],
  '区域未设置': [
    'Area not set',
    'Zone non définie',
    'Bereich nicht festgelegt',
    'Zone niet ingesteld',
    'Área sin definir',
    '영역 미설정',
    '領域未設定',
    'Area non impostata',
    'Область не задана',
  ],
  '画区中': [
    'Drawing area',
    'Tracé de la zone',
    'Bereich wird gezeichnet',
    'Zone tekenen',
    'Dibujando área',
    '영역 그리는 중',
    '領域描画中',
    'Disegno area',
    'Рисование области',
  ],
  '等待人体识别': [
    'Waiting for detection',
    'Détection en attente',
    'Warte auf Erkennung',
    'Wachten op detectie',
    'Esperando detección',
    '인체 인식 대기 중',
    '人物認識を待機中',
    'In attesa del rilevamento',
    'Ожидание распознавания',
  ],
  '全身在区域内': [
    'Body inside area',
    'Corps dans la zone',
    'Körper im Bereich',
    'Lichaam binnen zone',
    'Cuerpo dentro del área',
    '전신이 영역 안에 있음',
    '全身が領域内',
    'Corpo dentro l’area',
    'Тело внутри области',
  ],
  '关节越界': [
    'Body outside area',
    'Corps hors zone',
    'Körper außerhalb',
    'Lichaam buiten zone',
    'Cuerpo fuera del área',
    '신체가 영역을 벗어남',
    '身体が領域外',
    'Corpo fuori area',
    'Тело вне области',
  ],
  '画面中无人': [
    'No person detected',
    'Aucune personne détectée',
    'Keine Person erkannt',
    'Geen persoon gedetecteerd',
    'No se detecta ninguna persona',
    '사람이 감지되지 않음',
    '人物が見つかりません',
    'Nessuna persona rilevata',
    'Человек не обнаружен',
  ],
  '跟踪不完整': [
    'Tracking incomplete',
    'Suivi incomplet',
    'Tracking unvollständig',
    'Tracking onvolledig',
    'Seguimiento incompleto',
    '추적 불완전',
    '追跡が不完全',
    'Tracciamento incompleto',
    'Неполное отслеживание',
  ],
  '游戏时长': [
    'Game duration',
    'Durée du jeu',
    'Spieldauer',
    'Spelduur',
    'Duración del juego',
    '게임 시간',
    'ゲーム時間',
    'Durata del gioco',
    'Длительность игры',
  ],
  '{value} 分钟': [
    '{value} min',
    '{value} min',
    '{value} Min.',
    '{value} min',
    '{value} min',
    '{value}분',
    '{value}分',
    '{value} min',
    '{value} мин',
  ],
  '自定': [
    'Custom',
    'Personnalisé',
    'Eigene',
    'Aangepast',
    'Personalizado',
    '사용자 지정',
    'カスタム',
    'Personalizzato',
    'Своя',
  ],
  '返回前台，等待继续': [
    'Back in foreground, ready to resume',
    'Application active, prête à reprendre',
    'App aktiv, Fortsetzen möglich',
    'App actief, klaar om te hervatten',
    'Aplicación activa, lista para continuar',
    '앱으로 돌아왔습니다. 계속할 수 있습니다',
    'アプリに戻りました。再開できます',
    'App attiva, pronta a riprendere',
    'Приложение активно, можно продолжить',
  ],
  '摄像头中断，游戏已暂停': [
    'Camera interrupted; game paused',
    'Caméra interrompue, jeu en pause',
    'Kamera unterbrochen; Spiel pausiert',
    'Camera onderbroken; spel gepauzeerd',
    'Cámara interrumpida; juego en pausa',
    '카메라가 중단되어 게임이 일시 정지되었습니다',
    'カメラが中断されたため一時停止しました',
    'Fotocamera interrotta; gioco in pausa',
    'Камера отключена; игра приостановлена',
  ],
  '触发失败，游戏已暂停': [
    'Output failed; game paused',
    'Échec de sortie, jeu en pause',
    'Ausgabe fehlgeschlagen; Spiel pausiert',
    'Uitvoer mislukt; spel gepauzeerd',
    'Falló la salida; juego en pausa',
    '출력 실패로 게임이 일시 정지되었습니다',
    '出力失敗のため一時停止しました',
    'Uscita non riuscita; gioco in pausa',
    'Ошибка выхода; игра приостановлена',
  ],
  '游戏已暂停': [
    'Game paused',
    'Jeu en pause',
    'Spiel pausiert',
    'Spel gepauzeerd',
    'Juego en pausa',
    '게임 일시 정지',
    'ゲーム一時停止',
    'Gioco in pausa',
    'Игра приостановлена',
  ],
  '越界中，持续触发': [
    'Outside area; output active',
    'Hors zone ; sortie active',
    'Außerhalb; Ausgabe aktiv',
    'Buiten zone; uitvoer actief',
    'Fuera del área; salida activa',
    '영역 이탈, 출력 작동 중',
    '領域外・出力中',
    'Fuori area; uscita attiva',
    'Вне области; выход активен',
  ],
  '状态正常': [
    'Status normal',
    'État normal',
    'Status normal',
    'Status normaal',
    'Estado normal',
    '상태 정상',
    '状態正常',
    'Stato normale',
    'Состояние в норме',
  ],
  '游戏设置': [
    'Game settings',
    'Réglages du jeu',
    'Spieleinstellungen',
    'Spelinstellingen',
    'Ajustes del juego',
    '게임 설정',
    'ゲーム設定',
    'Impostazioni gioco',
    'Настройки игры',
  ],
  '关闭设置': [
    'Close settings',
    'Fermer les réglages',
    'Einstellungen schließen',
    'Instellingen sluiten',
    'Cerrar ajustes',
    '설정 닫기',
    '設定を閉じる',
    'Chiudi impostazioni',
    'Закрыть настройки',
  ],
  '分钟': ['min', 'min', 'Min.', 'min', 'min', '분', '分', 'min', 'мин'],
  '请输入 0.02 至 1440 分钟': [
    'Enter 0.02 to 1440 minutes',
    'Saisissez de 0,02 à 1440 minutes',
    '0,02 bis 1440 Minuten eingeben',
    'Voer 0,02 tot 1440 minuten in',
    'Introduce entre 0,02 y 1440 minutos',
    '0.02~1440분을 입력하세요',
    '0.02〜1440分を入力してください',
    'Inserisci da 0,02 a 1440 minuti',
    'Введите от 0,02 до 1440 минут',
  ],
  '开始前准备倒计时': [
    'Start countdown',
    'Compte à rebours',
    'Start-Countdown',
    'Aftellen voor start',
    'Cuenta atrás inicial',
    '시작 전 카운트다운',
    '開始前カウントダウン',
    'Conto alla rovescia',
    'Обратный отсчёт',
  ],
  '秒': ['sec', 's', 'Sek.', 'sec', 's', '초', '秒', 'sec', 'с'],
  '0 表示不倒计时，点击后立即开始': [
    '0 starts immediately without a countdown',
    '0 démarre immédiatement sans compte à rebours',
    '0 startet sofort ohne Countdown',
    '0 start direct zonder aftellen',
    '0 inicia de inmediato sin cuenta atrás',
    '0이면 카운트다운 없이 즉시 시작합니다',
    '0ならカウントダウンなしで開始します',
    '0 avvia subito senza conto alla rovescia',
    '0 запускает сразу без отсчёта',
  ],
  '请输入 0 至 30 秒': [
    'Enter 0 to 30 seconds',
    'Saisissez de 0 à 30 secondes',
    '0 bis 30 Sekunden eingeben',
    'Voer 0 tot 30 seconden in',
    'Introduce entre 0 y 30 segundos',
    '0~30초를 입력하세요',
    '0〜30秒を入力してください',
    'Inserisci da 0 a 30 secondi',
    'Введите от 0 до 30 секунд',
  ],
  '保存': [
    'Save',
    'Enregistrer',
    'Speichern',
    'Opslaan',
    'Guardar',
    '저장',
    '保存',
    'Salva',
    'Сохранить',
  ],
  '未连接': [
    'Disconnected',
    'Déconnecté',
    'Nicht verbunden',
    'Niet verbonden',
    'Desconectado',
    '연결 안 됨',
    '未接続',
    'Disconnesso',
    'Не подключено',
  ],
  '扫描中': [
    'Scanning',
    'Analyse en cours',
    'Suche läuft',
    'Scannen',
    'Buscando',
    '검색 중',
    'スキャン中',
    'Scansione',
    'Сканирование',
  ],
  '连接中': [
    'Connecting',
    'Connexion',
    'Verbindung läuft',
    'Verbinden',
    'Conectando',
    '연결 중',
    '接続中',
    'Connessione',
    'Подключение',
  ],
  '已连接': [
    'Connected',
    'Connecté',
    'Verbunden',
    'Verbonden',
    'Conectado',
    '연결됨',
    '接続済み',
    'Connesso',
    'Подключено',
  ],
  '连接异常': [
    'Connection error',
    'Erreur de connexion',
    'Verbindungsfehler',
    'Verbindingsfout',
    'Error de conexión',
    '연결 오류',
    '接続エラー',
    'Errore di connessione',
    'Ошибка подключения',
  ],
  '关闭设备设置': [
    'Close device settings',
    'Fermer les réglages de l’appareil',
    'Geräteeinstellungen schließen',
    'Apparaatinstellingen sluiten',
    'Cerrar ajustes del dispositivo',
    '기기 설정 닫기',
    'デバイス設定を閉じる',
    'Chiudi impostazioni dispositivo',
    'Закрыть настройки устройства',
  ],
  '一代电击': [
    'Generation 1',
    'Génération 1',
    'Generation 1',
    'Generatie 1',
    'Generación 1',
    '1세대',
    '第1世代',
    'Generazione 1',
    'Поколение 1',
  ],
  '二代电击': [
    'Generation 2',
    'Génération 2',
    'Generation 2',
    'Generatie 2',
    'Generación 2',
    '2세대',
    '第2世代',
    'Generazione 2',
    'Поколение 2',
  ],
  '波形曲线': [
    'Waveform',
    'Courbe d’onde',
    'Wellenform',
    'Golfvorm',
    'Forma de onda',
    '파형',
    '波形',
    'Forma d’onda',
    'Форма волны',
  ],
  '线性递增': [
    'Linear',
    'Linéaire',
    'Linear',
    'Lineair',
    'Lineal',
    '선형 증가',
    '線形増加',
    'Lineare',
    'Линейная',
  ],
  '渐强递增': [
    'Progressive',
    'Progressive',
    'Progressiv',
    'Progressief',
    'Progresiva',
    '점진 증가',
    '漸増',
    'Progressiva',
    'Прогрессивная',
  ],
  '阶梯递增': [
    'Stepped',
    'Par paliers',
    'Stufenweise',
    'Stapsgewijs',
    'Escalonada',
    '단계 증가',
    '段階増加',
    'A gradini',
    'Ступенчатая',
  ],
  'A 通道强度': [
    'Channel A intensity',
    'Intensité canal A',
    'Intensität Kanal A',
    'Intensiteit kanaal A',
    'Intensidad canal A',
    'A 채널 강도',
    'Aチャンネル強度',
    'Intensità canale A',
    'Интенсивность канала A',
  ],
  'B 通道强度': [
    'Channel B intensity',
    'Intensité canal B',
    'Intensität Kanal B',
    'Intensiteit kanaal B',
    'Intensidad canal B',
    'B 채널 강도',
    'Bチャンネル強度',
    'Intensità canale B',
    'Интенсивность канала B',
  ],
  '越界强度递增': [
    'Intensity increase outside area',
    'Augmentation hors zone',
    'Intensitätsanstieg außerhalb',
    'Intensiteitstoename buiten zone',
    'Aumento fuera del área',
    '영역 이탈 시 강도 증가',
    '領域外の強度増加',
    'Aumento fuori area',
    'Рост интенсивности вне области',
  ],
  '/ 秒': [
    '/ sec',
    '/ s',
    '/ Sek.',
    '/ sec',
    '/ s',
    '/ 초',
    '/ 秒',
    '/ sec',
    '/ с',
  ],
  '越界后立即持续输出，强度每秒叠加上述数值；回到区域内立即停止并恢复到基础强度。': [
    'Output starts immediately outside the area. Intensity increases by this value each second and resets on return.',
    'La sortie démarre immédiatement hors zone. L’intensité augmente chaque seconde et revient à la base au retour.',
    'Außerhalb startet die Ausgabe sofort. Die Intensität steigt pro Sekunde und wird bei Rückkehr zurückgesetzt.',
    'Buiten de zone start de uitvoer direct. De intensiteit stijgt per seconde en wordt bij terugkeer hersteld.',
    'La salida empieza al salir del área. La intensidad aumenta cada segundo y se restablece al volver.',
    '영역을 벗어나면 즉시 출력하며 매초 설정값만큼 증가하고 돌아오면 기본 강도로 복원됩니다.',
    '領域外ですぐ出力し、毎秒設定値だけ増加します。戻ると基本強度に戻ります。',
    'Fuori area l’uscita parte subito. L’intensità aumenta ogni secondo e si ripristina al rientro.',
    'Вне области выход включается сразу. Интенсивность растёт каждую секунду и сбрасывается при возврате.',
  ],
  '电量读取中': [
    'Reading battery',
    'Lecture de la batterie',
    'Akku wird gelesen',
    'Batterij wordt gelezen',
    'Leyendo batería',
    '배터리 확인 중',
    'バッテリー読取中',
    'Lettura batteria',
    'Чтение батареи',
  ],
  '电量 {value}%': [
    'Battery {value}%',
    'Batterie {value} %',
    'Akku {value} %',
    'Batterij {value}%',
    'Batería {value}%',
    '배터리 {value}%',
    'バッテリー {value}%',
    'Batteria {value}%',
    'Батарея {value}%',
  ],
  '断开': [
    'Disconnect',
    'Déconnecter',
    'Trennen',
    'Verbreken',
    'Desconectar',
    '연결 해제',
    '切断',
    'Disconnetti',
    'Отключить',
  ],
  '扫描设备': [
    'Scan devices',
    'Rechercher des appareils',
    'Geräte suchen',
    'Apparaten scannen',
    'Buscar dispositivos',
    '기기 검색',
    'デバイス検索',
    'Cerca dispositivi',
    'Искать устройства',
  ],
  '连接': [
    'Connect',
    'Connecter',
    'Verbinden',
    'Verbinden',
    'Conectar',
    '연결',
    '接続',
    'Connetti',
    'Подключить',
  ],
  '保存设备设置': [
    'Save device settings',
    'Enregistrer les réglages',
    'Geräteeinstellungen speichern',
    'Apparaatinstellingen opslaan',
    'Guardar ajustes del dispositivo',
    '기기 설정 저장',
    'デバイス設定を保存',
    'Salva impostazioni dispositivo',
    'Сохранить настройки',
  ],
  '游戏模式': [
    'Game mode',
    'Mode de jeu',
    'Spielmodus',
    'Spelmodus',
    'Modo de juego',
    '게임 모드',
    'ゲームモード',
    'Modalità di gioco',
    'Режим игры',
  ],
  '经典安全区': [
    'Classic zone',
    'Zone classique',
    'Klassische Zone',
    'Klassieke zone',
    'Zona clásica',
    '클래식 영역',
    'クラシックゾーン',
    'Zona classica',
    'Классическая зона',
  ],
  '木头人': [
    'Freeze game',
    'Jeu de l’immobilité',
    'Stopp-Spiel',
    'Stopspel',
    'Juego de estatuas',
    '무궁화 게임',
    'だるまさんがころんだ',
    'Gioco delle statue',
    'Замри',
  ],
  '缩圈模式': [
    'Shrinking zone',
    'Zone rétrécissante',
    'Schrumpfzone',
    'Krimpzone',
    'Zona menguante',
    '축소 영역',
    '縮小ゾーン',
    'Zona ristretta',
    'Сужающаяся зона',
  ],
  '指定姿势': [
    'Pose challenge',
    'Défi de pose',
    'Posen-Challenge',
    'Pose-uitdaging',
    'Reto de poses',
    '포즈 도전',
    'ポーズチャレンジ',
    'Sfida di pose',
    'Испытание поз',
  ],
  '闪避模式': [
    'Dodge mode',
    'Mode esquive',
    'Ausweichmodus',
    'Ontwijkmodus',
    'Modo esquiva',
    '회피 모드',
    '回避モード',
    'Modalità schivata',
    'Уклонение',
  ],
  '平衡挑战': [
    'Balance challenge',
    'Défi d’équilibre',
    'Balance-Challenge',
    'Balansuitdaging',
    'Reto de equilibrio',
    '균형 도전',
    'バランスチャレンジ',
    'Sfida di equilibrio',
    'Испытание равновесия',
  ],
  '连击模式': [
    'Combo mode',
    'Mode combo',
    'Combo-Modus',
    'Combomodus',
    'Modo combo',
    '콤보 모드',
    'コンボモード',
    'Modalità combo',
    'Режим комбо',
  ],
  '双区模式': [
    'Dual-zone mode',
    'Mode deux zones',
    'Doppelzonenmodus',
    'Dubbele zone',
    'Modo de doble zona',
    '이중 영역 모드',
    'デュアルゾーン',
    'Modalità doppia zona',
    'Режим двух зон',
  ],
  '自定义姿势': ['Custom pose'],
  '目标姿势已变化': ['Target pose changed'],
  '请立即修正动作': ['Correct your pose now'],
  '姿势正确': ['Pose correct'],
  '开始': ['Go'],
  '模式设置': ['Mode settings'],
  '木头人设置': ['Freeze-game settings'],
  '音乐可移动时间': ['Music / movement time'],
  '静止时间': ['Freeze time'],
  '每轮随机时间': ['Randomize every round'],
  '每轮在 1 秒到设置秒数之间随机': [
    'Each round uses a random duration from 1 second to the set maximum',
  ],
  '绘制目标姿势': ['Draw target pose'],
  '恢复默认姿势': ['Reset pose'],
  '拖动头、肩、肘、腕、髋、膝和脚踝关节点': [
    'Drag the head, shoulder, elbow, wrist, hip, knee and ankle joints',
  ],
  '姿势不匹配超过此时间才触发': ['Trigger only after the pose mismatches for this long'],
  '保存目标姿势': ['Save target pose'],
  '目标姿势': ['Target'],
  '已对齐': ['Aligned'],
  '需调整': ['Adjust'],
  '请进入画面': ['Step into the camera view'],
  '身体识别不完整': ['Body tracking is incomplete'],
  '姿势已对齐': ['Pose aligned'],
  '调整姿势 · {seconds} 秒后触发': ['Adjust your pose · triggers in {seconds} seconds'],
  '姿势预览不会触发设备输出': ['Pose preview never triggers device output'],
  '对齐自定义火柴人': ['Match the custom stick figure'],
  '未对齐目标姿势': ['Target pose not matched'],
  '本阶段剩余 {seconds} 秒': ['{seconds} seconds left in this phase'],
  '持续不匹配 {seconds} 秒后触发': [
    'Trigger after {seconds} seconds of continuous mismatch',
  ],
  '保持全身在安全区域内': ['Keep your whole body inside the safe zone'],
  '音乐播放：可以移动': ['Music playing: move freely'],
  '木头人：保持静止': ['Freeze: stay still'],
  '安全区域正在缩小': ['The safe zone is shrinking'],
  '闪避移动禁区': ['Dodge the moving blocked zone'],
  '双手展开并单脚站立': ['Extend both arms and stand on one leg'],
  '左侧留在 A 区，右侧留在 B 区': ['Keep your left side in A and your right side in B'],
  '举起左手': ['Raise your left hand'],
  '举起右手': ['Raise your right hand'],
  '抬起左腿': ['Lift your left leg'],
  '抬起右腿': ['Lift your right leg'],
  '保持下蹲': ['Hold a squat'],
  '双手展开': ['Extend both arms'],
  '准备姿势': ['Get ready'],
  '分数 / 连击': ['Score / combo'],
  '分数': ['Score'],
  '最长平衡': ['Longest balance'],
  '完成动作': ['Completed poses'],
  '木头人移动': ['Moved during freeze'],
  '姿势未完成': ['Pose not completed'],
  '碰到禁区': ['Touched blocked zone'],
  '失去平衡': ['Lost balance'],
  '进入错误区域': ['Entered the wrong zone'],
  '异常累计': [
    'Total abnormal time',
    'Temps anormal cumulé',
    'Gesamte Abweichungszeit',
    'Totale afwijkingstijd',
    'Tiempo anómalo total',
    '누적 이탈 시간',
    '累計異常時間',
    'Tempo anomalo totale',
    'Общее время нарушений',
  ],
  '最长安全时段': [
    'Longest safe stretch',
    'Plus longue période sûre',
    'Längste sichere Phase',
    'Langste veilige periode',
    'Mayor periodo seguro',
    '최장 안전 시간',
    '最長安全時間',
    'Periodo sicuro più lungo',
    'Самый долгий безопасный период',
  ],
  '越界 {outside} · 离开 {absent}': [
    'Outside {outside} · Absent {absent}',
    'Hors zone {outside} · Absent {absent}',
    'Außerhalb {outside} · Abwesend {absent}',
    'Buiten zone {outside} · Afwezig {absent}',
    'Fuera {outside} · Ausente {absent}',
    '영역 이탈 {outside} · 화면 이탈 {absent}',
    '領域外 {outside} · 画面外 {absent}',
    'Fuori area {outside} · Assente {absent}',
    'За границей {outside} · Нет в кадре {absent}',
  ],
  '违规 {outside} · 离开 {absent}': [
    'Violations {outside} · Absent {absent}',
    'Infractions {outside} · Absent {absent}',
    'Verstöße {outside} · Abwesend {absent}',
    'Overtredingen {outside} · Afwezig {absent}',
    'Infracciones {outside} · Ausente {absent}',
    '위반 {outside} · 화면 이탈 {absent}',
    '違反 {outside} · 画面外 {absent}',
    'Violazioni {outside} · Assente {absent}',
    'Нарушения {outside} · Нет в кадре {absent}',
  ],
  '左 {left} · 右 {right} · 双侧 {both}': [
    'Left {left} · Right {right} · Both {both}',
    'Gauche {left} · Droite {right} · Deux côtés {both}',
    'Links {left} · Rechts {right} · Beidseitig {both}',
    'Links {left} · Rechts {right} · Beide {both}',
    'Izquierda {left} · Derecha {right} · Ambos {both}',
    '왼쪽 {left} · 오른쪽 {right} · 양쪽 {both}',
    '左 {left} · 右 {right} · 両側 {both}',
    'Sinistra {left} · Destra {right} · Entrambi {both}',
    'Слева {left} · Справа {right} · Обе стороны {both}',
  ],
  '持续 {duration}': [
    'Duration {duration}',
    'Durée {duration}',
    'Dauer {duration}',
    'Duur {duration}',
    'Duración {duration}',
    '지속 {duration}',
    '継続 {duration}',
    'Durata {duration}',
    'Длительность {duration}',
  ],
  '左侧': [
    'Left side',
    'Côté gauche',
    'Linke Seite',
    'Linkerkant',
    'Lado izquierdo',
    '왼쪽',
    '左側',
    'Lato sinistro',
    'Левая сторона',
  ],
  '右侧': [
    'Right side',
    'Côté droit',
    'Rechte Seite',
    'Rechterkant',
    'Lado derecho',
    '오른쪽',
    '右側',
    'Lato destro',
    'Правая сторона',
  ],
  '双侧': [
    'Both sides',
    'Deux côtés',
    'Beide Seiten',
    'Beide kanten',
    'Ambos lados',
    '양쪽',
    '両側',
    'Entrambi i lati',
    'Обе стороны',
  ],
  '游戏结束': [
    'Game over',
    'Partie terminée',
    'Spiel beendet',
    'Spel afgelopen',
    'Juego terminado',
    '게임 종료',
    'ゲーム終了',
    'Gioco terminato',
    'Игра окончена',
  ],
  '实际游戏时长': [
    'Actual duration',
    'Durée réelle',
    'Tatsächliche Dauer',
    'Werkelijke duur',
    'Duración real',
    '실제 게임 시간',
    '実際の時間',
    'Durata effettiva',
    'Фактическое время',
  ],
  '模拟触发次数': [
    'Trigger count',
    'Nombre de déclenchements',
    'Anzahl Auslösungen',
    'Aantal triggers',
    'Número de activaciones',
    '작동 횟수',
    'トリガー回数',
    'Numero attivazioni',
    'Количество срабатываний',
  ],
  '触发记录': [
    'Trigger history',
    'Historique',
    'Auslösungsverlauf',
    'Triggergeschiedenis',
    'Historial',
    '작동 기록',
    'トリガー履歴',
    'Cronologia',
    'История срабатываний',
  ],
  '本局没有触发记录': [
    'No triggers in this session',
    'Aucun déclenchement',
    'Keine Auslösungen in dieser Runde',
    'Geen triggers in deze sessie',
    'Sin activaciones en esta sesión',
    '이번 게임에는 작동 기록이 없습니다',
    '今回はトリガー記録がありません',
    'Nessuna attivazione in questa sessione',
    'В этой сессии срабатываний нет',
  ],
  '离开画面': [
    'Left camera view',
    'Hors du champ',
    'Bild verlassen',
    'Buiten beeld',
    'Fuera de cámara',
    '화면 이탈',
    '画面外',
    'Fuori inquadratura',
    'Вне кадра',
  ],
  '再来一局': [
    'Play again',
    'Rejouer',
    'Noch einmal',
    'Opnieuw spelen',
    'Jugar de nuevo',
    '다시 하기',
    'もう一度',
    'Gioca di nuovo',
    'Играть снова',
  ],
  '重试': [
    'Retry',
    'Réessayer',
    'Erneut versuchen',
    'Opnieuw proberen',
    'Reintentar',
    '다시 시도',
    '再試行',
    'Riprova',
    'Повторить',
  ],
  '本机设置读取失败': [
    'Failed to read local settings',
    'Impossible de lire les réglages locaux',
    'Lokale Einstellungen konnten nicht gelesen werden',
    'Lokale instellingen konden niet worden gelezen',
    'No se pudieron leer los ajustes locales',
    '로컬 설정을 불러오지 못했습니다',
    '端末設定を読み込めませんでした',
    'Impossibile leggere le impostazioni locali',
    'Не удалось прочитать локальные настройки',
  ],
  '保持亮屏失败，请重试': [
    'Could not keep the screen awake. Retry.',
    'Impossible de garder l’écran allumé. Réessayez.',
    'Bildschirm konnte nicht aktiv gehalten werden.',
    'Scherm kon niet actief blijven.',
    'No se pudo mantener la pantalla activa.',
    '화면 켜짐 유지에 실패했습니다',
    '画面の常時点灯に失敗しました',
    'Impossibile mantenere lo schermo acceso',
    'Не удалось удерживать экран включённым',
  ],
  '设置保存失败，本次仍可继续': [
    'Could not save settings; this session can continue',
    'Échec de l’enregistrement ; la session peut continuer',
    'Speichern fehlgeschlagen; diese Runde kann fortgesetzt werden',
    'Opslaan mislukt; deze sessie kan doorgaan',
    'No se pudo guardar; la sesión puede continuar',
    '설정 저장에 실패했지만 현재 게임은 계속할 수 있습니다',
    '設定保存に失敗しましたが、このまま続行できます',
    'Salvataggio non riuscito; la sessione può continuare',
    'Не удалось сохранить; сессию можно продолжить',
  ],
  '区域太小，请重新画区': [
    'Area is too small. Draw it again.',
    'Zone trop petite. Redessinez-la.',
    'Bereich zu klein. Bitte neu zeichnen.',
    'Zone te klein. Teken opnieuw.',
    'El área es demasiado pequeña. Dibújala de nuevo.',
    '영역이 너무 작습니다. 다시 그리세요.',
    '領域が小さすぎます。描き直してください。',
    'Area troppo piccola. Ridisegnala.',
    'Область слишком мала. Нарисуйте снова.',
  ],
  '区域无效，请重新画区': [
    'Invalid area. Draw it again.',
    'Zone non valide. Redessinez-la.',
    'Ungültiger Bereich. Bitte neu zeichnen.',
    'Ongeldige zone. Teken opnieuw.',
    'Área no válida. Dibújala de nuevo.',
    '유효하지 않은 영역입니다. 다시 그리세요.',
    '無効な領域です。描き直してください。',
    'Area non valida. Ridisegnala.',
    'Недопустимая область. Нарисуйте снова.',
  ],
  '边界交叉，请重新画区': [
    'Boundary crosses itself. Draw it again.',
    'La limite se croise. Redessinez-la.',
    'Grenze überschneidet sich. Bitte neu zeichnen.',
    'De grens kruist zichzelf. Teken opnieuw.',
    'El límite se cruza. Dibújalo de nuevo.',
    '경계가 교차합니다. 다시 그리세요.',
    '境界が交差しています。描き直してください。',
    'Il confine si incrocia. Ridisegnalo.',
    'Граница пересекается. Нарисуйте снова.',
  ],
  '摄像头权限未开启，请在系统设置中允许访问': [
    'Camera permission is off. Allow it in system settings.',
    'Autorisez la caméra dans les réglages système.',
    'Kamerazugriff in den Systemeinstellungen erlauben.',
    'Sta cameratoegang toe in de systeeminstellingen.',
    'Permite la cámara en los ajustes del sistema.',
    '시스템 설정에서 카메라 권한을 허용하세요.',
    'システム設定でカメラを許可してください。',
    'Consenti la fotocamera nelle impostazioni di sistema.',
    'Разрешите доступ к камере в настройках системы.',
  ],
  '摄像头不可用，请重试': [
    'Camera unavailable. Retry.',
    'Caméra indisponible. Réessayez.',
    'Kamera nicht verfügbar. Erneut versuchen.',
    'Camera niet beschikbaar. Probeer opnieuw.',
    'Cámara no disponible. Reintenta.',
    '카메라를 사용할 수 없습니다. 다시 시도하세요.',
    'カメラを利用できません。再試行してください。',
    'Fotocamera non disponibile. Riprova.',
    'Камера недоступна. Повторите попытку.',
  ],
  '人体识别暂不可用，请重试': [
    'Body detection unavailable. Retry.',
    'Détection indisponible. Réessayez.',
    'Körpererkennung nicht verfügbar.',
    'Lichaamsdetectie niet beschikbaar.',
    'Detección corporal no disponible.',
    '인체 인식을 사용할 수 없습니다.',
    '人物認識を利用できません。',
    'Rilevamento non disponibile.',
    'Распознавание тела недоступно.',
  ],
  '蓝牙权限被永久拒绝，请到系统设置中开启': [
    'Bluetooth permission is blocked. Enable it in system settings.',
    'Autorisation Bluetooth bloquée. Activez-la dans les réglages.',
    'Bluetooth-Berechtigung blockiert. In den Einstellungen aktivieren.',
    'Bluetooth-toegang geblokkeerd. Schakel die in via instellingen.',
    'Permiso Bluetooth bloqueado. Actívalo en ajustes.',
    '블루투스 권한이 차단되었습니다. 시스템 설정에서 허용하세요.',
    'Bluetooth権限が拒否されています。設定で許可してください。',
    'Permesso Bluetooth bloccato. Abilitalo nelle impostazioni.',
    'Разрешение Bluetooth заблокировано. Включите его в настройках.',
  ],
  '蓝牙权限未允许': [
    'Bluetooth permission not granted',
    'Autorisation Bluetooth refusée',
    'Bluetooth-Berechtigung fehlt',
    'Bluetooth-toegang niet toegestaan',
    'Permiso Bluetooth no concedido',
    '블루투스 권한이 허용되지 않음',
    'Bluetooth権限がありません',
    'Permesso Bluetooth non concesso',
    'Нет разрешения Bluetooth',
  ],
  '请先开启手机蓝牙': [
    'Turn on Bluetooth first',
    'Activez d’abord le Bluetooth',
    'Bluetooth zuerst einschalten',
    'Zet Bluetooth eerst aan',
    'Activa primero el Bluetooth',
    '먼저 블루투스를 켜세요',
    'Bluetoothをオンにしてください',
    'Attiva prima il Bluetooth',
    'Сначала включите Bluetooth',
  ],
  '请先开启手机定位服务': [
    'Turn on location services first',
    'Activez d’abord la localisation',
    'Standortdienste zuerst aktivieren',
    'Zet locatieservices eerst aan',
    'Activa primero la ubicación',
    '먼저 위치 서비스를 켜세요',
    '位置情報サービスをオンにしてください',
    'Attiva prima la localizzazione',
    'Сначала включите геолокацию',
  ],
  '当前手机不支持蓝牙低功耗设备': [
    'This phone does not support Bluetooth LE',
    'Ce téléphone ne prend pas en charge Bluetooth LE',
    'Dieses Telefon unterstützt Bluetooth LE nicht',
    'Deze telefoon ondersteunt Bluetooth LE niet',
    'Este teléfono no admite Bluetooth LE',
    '이 휴대폰은 Bluetooth LE를 지원하지 않습니다',
    'この端末はBluetooth LEに対応していません',
    'Questo telefono non supporta Bluetooth LE',
    'Телефон не поддерживает Bluetooth LE',
  ],
  '蓝牙状态不可用': [
    'Bluetooth status unavailable',
    'État Bluetooth indisponible',
    'Bluetooth-Status nicht verfügbar',
    'Bluetooth-status niet beschikbaar',
    'Estado Bluetooth no disponible',
    '블루투스 상태를 확인할 수 없음',
    'Bluetooth状態を確認できません',
    'Stato Bluetooth non disponibile',
    'Статус Bluetooth недоступен',
  ],
  '扫描设备失败': [
    'Device scan failed',
    'Échec de la recherche',
    'Gerätesuche fehlgeschlagen',
    'Scannen mislukt',
    'Error al buscar dispositivos',
    '기기 검색 실패',
    'デバイス検索に失敗しました',
    'Ricerca dispositivi non riuscita',
    'Ошибка поиска устройств',
  ],
  'EMS 设备已断开': [
    'EMS device disconnected',
    'Appareil EMS déconnecté',
    'EMS-Gerät getrennt',
    'EMS-apparaat verbroken',
    'Dispositivo EMS desconectado',
    'EMS 기기 연결이 끊어졌습니다',
    'EMSデバイスが切断されました',
    'Dispositivo EMS disconnesso',
    'Устройство EMS отключено',
  ],
  '连接设备失败': [
    'Connection failed',
    'Échec de la connexion',
    'Verbindung fehlgeschlagen',
    'Verbinding mislukt',
    'Error de conexión',
    '기기 연결 실패',
    '接続に失敗しました',
    'Connessione non riuscita',
    'Ошибка подключения',
  ],
  'EMS 设备未连接': [
    'EMS device is not connected',
    'Appareil EMS non connecté',
    'EMS-Gerät ist nicht verbunden',
    'EMS-apparaat is niet verbonden',
    'El dispositivo EMS no está conectado',
    'EMS 기기가 연결되지 않았습니다',
    'EMSデバイスが未接続です',
    'Dispositivo EMS non connesso',
    'Устройство EMS не подключено',
  ],
  'EMS 强度必须大于 0': [
    'EMS intensity must be above 0',
    'L’intensité EMS doit être supérieure à 0',
    'EMS-Intensität muss größer als 0 sein',
    'EMS-intensiteit moet hoger zijn dan 0',
    'La intensidad EMS debe ser mayor que 0',
    'EMS 강도는 0보다 커야 합니다',
    'EMS強度は0より大きくしてください',
    'L’intensità EMS deve essere maggiore di 0',
    'Интенсивность EMS должна быть больше 0',
  ],
  '设备状态监听失败': [
    'Device status monitoring failed',
    'Échec du suivi de l’appareil',
    'Gerätestatus konnte nicht überwacht werden',
    'Apparaatstatus volgen mislukt',
    'Error al supervisar el dispositivo',
    '기기 상태 감시 실패',
    'デバイス状態の監視に失敗しました',
    'Monitoraggio dispositivo non riuscito',
    'Ошибка отслеживания устройства',
  ],
  'EMS 指令发送失败': [
    'Failed to send EMS command',
    'Échec de l’envoi de la commande EMS',
    'EMS-Befehl konnte nicht gesendet werden',
    'EMS-opdracht verzenden mislukt',
    'Error al enviar el comando EMS',
    'EMS 명령 전송 실패',
    'EMSコマンド送信に失敗しました',
    'Invio comando EMS non riuscito',
    'Не удалось отправить команду EMS',
  ],
};

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const delegate = _AppLocalizationsDelegate();

  String text(String source, [Map<String, Object?> values = const {}]) {
    var result = source;
    final index = _languageIndexes[locale.languageCode];
    if (index != null) {
      final translations = _translations[source];
      if (translations != null && index < translations.length) {
        result = translations[index];
      } else {
        result = _translations[source]?.first ?? source;
      }
    }
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return result;
  }

  String message(String source) {
    if (source.startsWith('设备报告协议错误：')) {
      final code = source.substring('设备报告协议错误：'.length);
      return '${text('Device protocol error')}: $code';
    }
    return text(source);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => supportedAppLocales.any(
    (value) => value.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class AppLocaleController extends ChangeNotifier {
  static const _preferenceKey = 'app_locale';

  Locale _locale = supportedAppLocales.first;
  bool _disposed = false;

  Locale get locale => _locale;

  Future<void> load() async {
    try {
      final preferences = await SharedPreferences.getInstance();
      final code = preferences.getString(_preferenceKey);
      Locale? locale;
      for (final value in supportedAppLocales) {
        if (value.languageCode == code) {
          locale = value;
          break;
        }
      }
      if (!_disposed && locale != null && locale != _locale) {
        _locale = locale;
        notifyListeners();
      }
    } on Object {
      // 语言设置读取失败时继续使用中文，不阻止应用启动。
    }
  }

  Future<void> setLocale(Locale locale) async {
    if (!supportedAppLocales.any(
      (value) => value.languageCode == locale.languageCode,
    )) {
      return;
    }
    if (_locale != locale) {
      _locale = locale;
      notifyListeners();
    }
    try {
      final preferences = await SharedPreferences.getInstance();
      await preferences.setString(_preferenceKey, locale.languageCode);
    } on Object {
      // 保存失败不影响本次语言切换。
    }
  }

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }
}
